services:
  backend:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=test

  db:
    container_name: db
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
