services:
  backend:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  
  db:
    container_name: db
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
