# Generated by Django 4.2.5 on 2023-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_verify_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
