# Generated by Django 4.2.6 on 2023-10-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profileuser_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('send_mail', 'Can Send Email to users'),)},
        ),
    ]
